### ISSUE TITLE
[Bug/Evo] Couleurs des âges des joueurs U-20

### ISSUE THREAD

**Issue by LA-alpacstily** [hattrick-french-dtn/dtn-interface#103]
Bug n°1 : Après investigation dans le code, la couleur des U-20 n'est pas conforme au code-couleur de Tibbs : il manque notamment le gris et l'olive (quel dommage)
![image](https://user-images.githubusercontent.com/51236354/60707675-8e758080-9f0c-11e9-9406-33dde51bb83a.png)

Evo : Pour une meilleure visibilité des carac, il serait bien que ces couleurs ne soient appliquées que sur l'âge, et pas toute la ligne

Bug n°2 : depuis ce matin (05/07/2019), certains joueurs qui étaient orange apparaissent désormais en vert, les couleurs de Tibbs ne sont donc plus appliquées :
![image](https://user-images.githubusercontent.com/51236354/60707894-0ba0f580-9f0d-11e9-9106-5b8fee6ce176.png)

**Comment by keseru44** [comment]
Je vais plutôt virer les couleurs et ajouter le dernier match possible pour les u20 dans la Fiche Résumé #79
