### ISSUE TITLE
[Evolution] Mise à jour des minimas via HTMS

### ISSUE THREAD

**Issue by LA-alpacstily** [hattrick-french-dtn/dtn-interface#11]
Remplacer les minima d'il y a 15 ans par ceux-ci basés sur le potentiel HTMS.
Si un joueur a moins de 28.0 ans
- si G>5 et si potentielHTMS>1750 : on garde
- si G<6 et si potentielHTMS>1950 : on garde
Si un joueur a plus de 28.0 ans
- si G>5 et si niveauHTMS>1800 : on garde
- si G<6 et si niveauHTMS>2000 : on garde

**Comment by keseru44** [comment]
Pour les 17-20ans
Pour les joueurs de champs,  ne prendre que les joueurs minimum à htms 2050 sans spé et htms 2000 avec spé.
