### ISSUE TITLE
[Evolution] Fiche résumé Slack

### ISSUE THREAD

**Issue by Eremanth** [hattrick-french-dtn/dtn-interface#124]
Quelque chose du genre

`:smile: *Didier Borot* _24 ans et 45 jours_ (C/P/D/B/E) _*14+6*_ / 10+0 / 13+0 / 4+0 / 5 / Xp 6 / *Rap* / HTMS foxtrick 1514 (2016)
 _(https://www.hattrick.org/goto.ashx?path=/Club/Players/Player.aspx?playerId=426883131)_`

**Comment by LA-alpacstily** [comment]
PR #125
