### ISSUE TITLE
[Evolution] Avoir un bouton pour purger automatiquement les joueurs en dessous d'un certain HTMS

### ISSUE THREAD

**Issue by LA-alpacstily** [hattrick-french-dtn/dtn-interface#131]
- Evolution à faire une fois toutes les MaJ du secteur archivés réalisés
- A faire pour les joueurs de plus de 20 ans
- Seuil HTMS à définir avec les DTN+ (ex : 1500 HTMS pour les gardiens, 1700 HTMS pour les joueurs de champ)
- Bouton pour pouvoir lancer cette purge une fois par saison (au moins par les admin)

**Comment by KCelec** [comment]
Faut faire gaffe, si on a pas le scan on risque de purger un joueur à tort.
Le TSI (absolu) est un indicateur plus fiable.

**Comment by LA-alpacstily** [comment]
Remplacé par purge en fonction du TSI.
