### ISSUE TITLE
[Evolution] Chercher joueur par ID

### ISSUE THREAD

**Issue by KCelec** [hattrick-french-dtn/dtn-interface#139]
Quand on rentre l'ID d'un joueur sur la page Chercher joueur, ce serait mieux si on était directement redirigé vers la page du joueur (éventuellement ouverte dans un nouvel onglet).

**Comment by Eremanth** [comment]
Je pense que je vais ajouter un champ de recherche sur le menu d'en haut à gauche valable partout sur le site.

**Comment by LA-alpacstily** [comment]
Fait dans PR #167
