### ISSUE TITLE
[Evolution] Ajouter aux admin la fonction choix du sélectionneur (A ou U20)

### ISSUE THREAD

**Issue by LA-alpacstily** [hattrick-french-dtn/dtn-interface#14]
Le compte perso de Eremanth, sélectionneur actuel A, est relié à la sélection U20 pas A, du coup impossible de faire les màj depuis la sélection nationale. 
Il existe un compte 'coachA' mais il est relié au compte HT de polatch, ce qui fait que ça ne fonctionne pas non plus (puisque Polatch n'est plus le coach :p)

Donc il faut soit modifier le compte coachA pour qu'il soit lié au compte HT de Eremanth, soit modifier le compte d'Eremanth pour qu'il pointe bien vers la sélection NT A

**Comment by keseru44** [comment]
Tenter de faire cette mise à jour dans la bdd.
update dtn_htfff.ht_admin set passAdmin = '1234', idAdminHT='9839467',emailAdmin='paladinrouge@orange.fr' where loginAdmin = 'coachA';

**Comment by bpetto35** [comment]
Pour corriger, il faut modifier la bdd directement.
Il faut un accès ssh au serveur. Pour celà, il faut me faire une demande pour que je crée un compte utilisateur, etc ...

Pour la bdd, il y a un backup tous les lundis à 3h du matin.

**Comment by keseru44** [comment]
Je pense qu'il faudrait également un bouton/une option pour faire ça automatiquement dans un endroit qui n'est accessible que par l'administrateur. Il faut que ça soit plus pratique. Mais où?

**Comment by bpetto35** [comment]
Voilà, ce que j'ai dans la base au 3 juin dernier
loginAdmin | idNiveauAcces_fk | selection | idPosition_fk
-- | -- | -- | --
CoachA | 4 | A | NULL
CoachU20 | 0 | U20 | NULL
test_CoachA | 4 | test_A | 6
selectionneurU20 | 4 | U20 | 6

Donc, on souhaite faire pointer CoachA vers les infos d'Eremanth, c'est bien ça ?

**Comment by bpetto35** [comment]
Ce que je ne comprends pas, c'est que normalement le DTN# doit pouvoir mettre les droits aux sélectionneurs.
Faire la bidouille dans la bdd ce n'est pas très efficace. Que s'est-il passé pour que les infos soient bancale ?

**Comment by bpetto35** [comment]
J'ai effectué la requête de mise à jour sur la bdd.

**Comment by keseru44** [comment]
On a quelles infos dans la base normalement?
Il faudrait demander l'info au dtn# pour savoir ce qu'il a fait la dernière fois. C'est bien walde, c'est ça ?

**Comment by Eremanth** [comment]
Walde indique qu'il peut passer un compte "sélectionneur" mais qu'il ne peut pas choisir entre u20 et A.

**Comment by bpetto35** [comment]
Ok, je vais regarder si on peut ajouter facilement une dropbox ou coche pour faire le choix en A et U20

**Comment by Eremanth** [comment]
@bpetto35 Je viens de faire le test avec le compte CoachA que tu as relié à mon compte, lorsque je clique sur charger les données (coach_dtn_submitting) ça ne fait rien, je me retrouve sur une page blanche. Pourtant il y a bien des joueurs dans l'équipe de France.
