### ISSUE TITLE
[Evolution] Crypter les mots de passe

### ISSUE THREAD

**Issue by KCelec** [hattrick-french-dtn/dtn-interface#141]
Tout est dans le titre
(au moins, prévenir l'utilisateur au moment où il configure son MDP)

**Comment by KCelec** [comment]
Et mettre un message de confirmation quand on change le MDP

**Comment by LA-alpacstily** [comment]
Traité via PR #166 .
Pour info, sur le chiffrement des mots de passe, ya eu pas mal de boulot de fait, voilà la liste précise :
Chiffrement à la connexion (Tout le monde)
Cryptage lors de la création ou la modification des comptes (DTN#)
Cryptage lors de l'édition d'un compte sélectionneur (DTN#)
Sécurisation du changement de mot de passe (Tout le monde)
Remplacement affichage mdp par mail des utilisateurs pour les Admins  (DTN#)
