### ISSUE TITLE
[Evolution] Plus de joueurs archivés sans secteur

### ISSUE THREAD

**Issue by KCelec** [hattrick-french-dtn/dtn-interface#146]
Supprimer la possibilité pour tout le monde de sortir du secteur un joueur archivé, et affecter (sur la base des caras connues) les joueurs actuellement archivés sans secteur.
Supprimer également la possibilité d'archiver un joueur sans secteur si elle existe (peut-être pour les admins).
Actuellement l'état Archivé sans secteur est un puits, seuls les admins peuvent en bouger le joueur

**Comment by LA-alpacstily** [comment]
Traité via PR #150  + ménage fait dans la base du secteur des joueurs archivés.
