### ISSUE TITLE
[Evolution] Rajouter la colonne TSI dans le tableau de "Ma Liste"

### ISSUE THREAD

**Issue by drumtoon** [hattrick-french-dtn/dtn-interface#156]
Le titre est assez explicite...
Perso je la mettrais à la place de la colonne "Valeur HTMS", que je trouve inutile

**Comment by Eremanth** [comment]
@drumtoon la valeur HTMS est très utile pour comparer les joueurs après 28 ans, lorsque le potentiel HTMS n'a plus d'importance. Mais je peux rajouter le TSI effectivement.
