### ISSUE TITLE
[Evolution] Ajout joueurs hors minima par DTN+

### ISSUE THREAD

**Issue by LA-alpacstily** [hattrick-french-dtn/dtn-interface#16]
Parfois certains joueurs ne peuvent être ajoutés car ne respectent les minimas (cf Issue #11).

Il faudrait permettre aux DTN+ (seulement eux, pour éviter un ajout compulsif de joueurs par un DTN newbie) de pouvoir tout de même ajouter le joueur.

**Comment by Eremanth** [comment]
#18

**Comment by Eremanth** [comment]
PR #26
