### ISSUE TITLE
[Bug] Onglets à harmoniser sur fiche joueur autre secteur

### ISSUE THREAD

**Issue by KCelec** [hattrick-french-dtn/dtn-interface#163]
(pas très urgent)
Quand un DTN+ visite la Fiche Consultation d'un joueur qui n'est pas de son secteur, il voit les mêmes onglets que sur un joueur de son secteur :
![image](https://user-images.githubusercontent.com/52796015/61295608-b4d2d000-a7d8-11e9-9936-563d73e43db1.png)
En particulier, il voit l'onglet Fiche DTN qui est inaccessible pour lui (seul onglet dans ce cas) :
![image](https://user-images.githubusercontent.com/52796015/61295762-1430e000-a7d9-11e9-848b-d8d1ca02a920.png)
Les autres onglets sont tous accessibles, mais une fois sur la page Matchs (ou Commentaires, ou Fiche Forum, ou Fiche Résumé, ou etc) des onglets accessibles ne sont pas affichés :
![image](https://user-images.githubusercontent.com/52796015/61295985-80134880-a7d9-11e9-94fb-ccb88902baac.png)

**Comment by LA-alpacstily** [comment]
Problème traité via PR #181 et #185.
Affichage d'un menu unique quelque soit les onglets.
