### ISSUE TITLE
[Bug] Fixer l'alignement sur la Fiche Consultation

### ISSUE THREAD

**Issue by KCelec** [hattrick-french-dtn/dtn-interface#165]
Je m'y connais pas trop donc je serais incapable de donner un nom à ce phénomène, mais :
![image](https://user-images.githubusercontent.com/52796015/61297895-7ee41a80-a7dd-11e9-93cf-0939e9c169d1.png)
![image](https://user-images.githubusercontent.com/52796015/61297920-8e636380-a7dd-11e9-92a0-d7f10c4783ad.png)
Comme on peut le voir en comparant ces deux fiches joueurs (prendre le tableau Historique des modifications/remarques comme point de repère), la position des barres de cara varie (et je pense qu'elle dépend de la longueur de la barre maximale).
Cela serait bien de fixer ça, et de diminuer l'écart entre les barres de caras et les noms des dénominations à droite parce que là il y a la place pour 50 petits carrés.

**Comment by LA-alpacstily** [comment]
Traité dans PR #211
