### ISSUE TITLE
[Bug] Problème joueurs non présents sur l'option rechercher

### ISSUE THREAD

**Issue by keseru44** [hattrick-french-dtn/dtn-interface#196]
Dans l'onglet recherche, polatch ne trouve pas ses joueurs alors qu'ils sont bien en base
Silvain Tessier (444445891) 17 ans et 14 jours (G/D/CF/E) 7+0 / 4+0 / 5+0 / 5 / Xp 2 / HTMS caracs 179 (1800) / Dern. Modif : 2 jours [19/07/2019]
Bernard Rigaud (444528997) 17 ans et 8 jours (G/D/CF/E) 7+0 / 5+0 / 2+0 / 4 / Xp 1 / HTMS caracs 199 (1829) / Dern. Modif : 6 jours [15/07/2019]

**Comment by LA-alpacstily** [comment]
Fait dans PR #214
