### ISSUE TITLE
[Evolution] Modification options par défaut dans Fiches Résumés

### ISSUE THREAD

**Issue by LA-alpacstily** [hattrick-french-dtn/dtn-interface#2]
Concernant les fiches résumés : 
- pour les Fw et Fwtw, rajouter par défaut la construction dans les carac affichées : "Fw (B/P/A/C)" au lieu de "Fw (B/P/A)" et "Fw (B/P/A/C)" au lieu de "Fwtw (B/A/P)" 
- pour les milieux : rajouter dans les carac affichées : "IM (C/P/D/B)" au lieu de "IM (C/P/D)"

- Rajouter une option "TDL (D/C/B/CF)"
- Rajouter une option IM def (milieu def) correspondant aux carac actuelles "IMdef (C/P/D)"
- Rajouter une option IMtw (milieu vers l'aile) "IMtw (C/A/D/P)"

**Comment by keseru44** [comment]
Je rajouterais bien le cf pour les gardiens.

**Comment by LA-alpacstily** [comment]
Suite à ce qu'on s'est dit sur le slack:
- Supprimer le Fwtw qui a les memes carac que le Fw désormais (B/P/A/C)
- cocher par défaut le HTMS foxtrick (celui en bas à gauche du 2nd cadre)
- afficher l'endurance par défaut uniquement pour les 19-20 ans et les plus de 27 ans
- afficher le CF par défaut uniquement pour les plus de 27 ans

**Comment by LA-alpacstily** [comment]
Autre option, à afficher sur la Fiche consultation et la Fiche DTN du joueur, pour les moins de 20 ans et 111 jours : le dernier match de qualif / CdM que le joueur peut jouer (info affichée par Foxtrick sur la page d'un joueur).
Exemple : CdM XXX - Tour I - #14

Voir le code source de Foxtrick pour récupérer le code.

**Comment by keseru44** [comment]
Je refais une issue pour les le dernier match de qualif.
Le reste est fait selon les modifs de dernière minutes donnés sur le slack

**Comment by keseru44** [comment]
#78
