### ISSUE TITLE
Changer l'âge mini/maxi des MaJ secteur suite au passage U20/U21

### ISSUE THREAD

**Issue by LA-alpacstily** [hattrick-french-dtn/dtn-interface#262]
Vu que les U20 deviennent des U21, il faudra faire évoluer les MaJ secteur --> - MaJ secteurs U20 à transformer en U21 (21 ans et 112 jours) et les MaJ secteurs A démarreront à partir de 22 ans et 0 jours. A faire pour début 2021.

**Comment by Eremanth** [comment]
#280
