### ISSUE TITLE
MaJ du bouton "Envoyer un MP" sur la fiche du joueur

### ISSUE THREAD

**Issue by LA-alpacstily** [hattrick-french-dtn/dtn-interface#273]
Lorsque l'on clique sur le bouton enveloppe "Envoyer un MP" sur la fiche du joueur, on arrive sur la page du manager, et non sur la page HT-mail permettant d'envoyer un MP.
Pour un joueur pris au pif, l'URL où on arrive se termine par "/Club/Manager/?teamId=722821"
Alors que cela économiserait un clic si on arrivait directement sur "/MyHattrick/Inbox/?actionType=newMail&userId=13167940"

**Comment by LA-alpacstily** [comment]
EremanthAujourd’hui à 13:49
Quand j'ajoute "/Inbox/?actionType=newMail&userId=1234" je suis renvoyé vers la page de manager. Pourtant sur Portal, le lien affiché en hoover est bien celui-là et ça fonctionne

AlpaAujourd’hui à 13:51
@Eremanth et si tu ajoutes "/MyHattrick/Inbox/?actionType=newMail&userid=1234"
En hoover sur Portal il y a "/MyHattrick" juste avant
Et le "&" est écrit comme "%26"

**Comment by Eremanth** [comment]
Réglé par #275
