### ISSUE TITLE
[Evolution] Maj des joueurs sans secteurs

### ISSUE THREAD

**Issue by keseru44** [hattrick-french-dtn/dtn-interface#48]
Mettre à jour les joueurs sans secteur défini (soit lors d'une mise à jour de secteur - avec ou sans case à cocher ; soit avec une option à part)

**Comment by LA-alpacstily** [comment]
C'est déjà fonctionnel en tant qu'admin avec la MaJ scindée d'Eremanth.
Reste à la rendre oper pour les DTN+ j'imagine

**Comment by LA-alpacstily** [comment]
PR #105
