### ISSUE TITLE
[Evolution] Ajout du taux d'endurance dans l'export excel de maliste.php

### ISSUE THREAD

**Issue by keseru44** [hattrick-french-dtn/dtn-interface#50]
Peut-on ajouter une colonne "taux d'endurance" dans la liste des joueurs qu'on suit. Donc dans maliste.php.

Ça permettra de voir plus facilement si on a des problèmes de suivi.

**Comment by Eremanth** [comment]
Euh ça, ça existe déjà, non ? Ou alors je comprends pas de quoi tu parles

**Comment by LA-alpacstily** [comment]
Fait dans PR #54
