### ISSUE TITLE
[Evolution] Encodage des caractères

### ISSUE THREAD

**Issue by Eremanth** [hattrick-french-dtn/dtn-interface#53]
Ya des problèmes d'encodage un peu partout (dans les sorties Excel notamment) liés aux accents et autres caractères spéciaux (noms étrangers, etc).

**Comment by LA-alpacstily** [comment]
Cela revient à priori selon keseru à passer en utf-8. Priorité basse, je confirme ^^

**Comment by LA-alpacstily** [comment]
Traitée par Eremanth, passée en prod.
